### 1. POST
POST localhost:8080/api/save
Content-Type: application/json

{
  "title": "algo",
  "tags": [
      {"name": "algo1"},
      {"name": "algo2"},
      {"name": "algo3"},
      {"name": "algo4"}
  ]
}

### 2. GET
GET localhost:8080/api/1
Accept: application/json

### 3. DELETE
DELETE localhost:8080/api/1